#!/bin/bash

project_path=$1
safer_report_path=$2

current_path=$(pwd)
cd $project_path
commit=$(git rev-parse HEAD)

safer_results=$(grep -A7 "Number of dependencies with vulnerabilities:" $safer_report_path)

safer_report_log_gist=$(gh gist create $safer_report_path --public --desc "Safer report log")

issue_link=$(
  gh issue create \
    --title "Safer automation" \
    --body "$(cat <<EOF
Hi,
We're from [Safer Team](https://gitlab.com/lsi-ufcg/vulnerabilidades/safer)
Safer is an open-source application designed to identify and mitigate vulnerabilities in software dependencies

Our approach addresses the challenge developers face in keeping their project dependencies up-to-date in order to mitigate the risk of security vulnerabilities associated with outdated versions.

The system automatically updates project dependencies using a heuristic designed to select the most secure, stable, and compatible versions for your project.

We want to contribute with the open source community using our tool

Here is the report generated by safer:
[safer-report]($safer_report_log_gist)

Safer runned in this version of the app: $commit

$safer_results

You can reply this issue if you have any questions and we'll answer you as soon as possible

Thanks,
Safer Team
EOF
)"
)
echo $issue_link $commit
issue_number=$(basename $issue_link)
main_branch=$(git rev-parse --abbrev-ref HEAD)
git checkout safer-result > /dev/null 2>&1

gh pr create --title "Updated pom.xml generated by Safer" \
  --body "$(cat <<EOF
This PR updates dependencies versions in order to decrease the number of vulnerabilities.

See #$issue_number
EOF
)" \
  --base $main_branch
  >&2

cd $current_path
