#!/bin/bash

project_path=$1
safer_report_path=$2

current_path=$(pwd)
cd $project_path

safer_report_log_gist=$(gh gist create $safer_report_path --public --desc "Safer report log")

issue_link=$(
  gh issue create \
    --title "Safer automation" \
    --body "Here is the report generated by safer:\n[safer-report]($safer_report_log_gist)")

issue_number=$(basename $issue_link)
main_branch=$(git rev-parse --abbrev-ref HEAD)
git checkout safer-result

gh pr create --title "Updated pom.xml generated by Safer" \
  --body "$(cat <<EOF
This PR updates dependencies versions in order to decrease the number of vulnerabilities.

See #$issue_number
EOF
)" \
  --base $main_branch

cd $current_path

# Usage: ./bash/submit-artifacts-github.sh /home/cristovao/codes/playground/github-cli-playground /home/cristovao/codes/lsi/security/safer-reproduction-kit/outputs/stdout/antikythera.txt
